# Generated by Django 2.2.16 on 2022-10-26 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введен неверный формат', regex='[^/w]+')], verbose_name='Имя пользователя'),
        ),
    ]
